// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package models

import (
	"context"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
    pos_id, price, recipe_id
) VALUES (
    $1, $2, $3
) RETURNING id, pos_id, price, recipe_id, created_at
`

type CreateOrderParams struct {
	PosID    int32
	Price    int32
	RecipeID int32
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.PosID, arg.Price, arg.RecipeID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.PosID,
		&i.Price,
		&i.RecipeID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteOrder = `-- name: DeleteOrder :exec
DELETE FROM orders
WHERE id = $1
`

func (q *Queries) DeleteOrder(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteOrder, id)
	return err
}

const getOrder = `-- name: GetOrder :one
SELECT id, pos_id, price, recipe_id, created_at FROM orders
WHERE id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.PosID,
		&i.Price,
		&i.RecipeID,
		&i.CreatedAt,
	)
	return i, err
}

const listOrder = `-- name: ListOrder :many
SELECT id, pos_id, price, recipe_id
FROM orders
LIMIT $1 OFFSET $2
`

type ListOrderParams struct {
	Limit  int32
	Offset int32
}

type ListOrderRow struct {
	ID       int64
	PosID    int32
	Price    int32
	RecipeID int32
}

func (q *Queries) ListOrder(ctx context.Context, arg ListOrderParams) ([]ListOrderRow, error) {
	rows, err := q.db.Query(ctx, listOrder, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOrderRow
	for rows.Next() {
		var i ListOrderRow
		if err := rows.Scan(
			&i.ID,
			&i.PosID,
			&i.Price,
			&i.RecipeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrder = `-- name: UpdateOrder :one
UPDATE orders
SET pos_id = $2,
    price = $3,
    recipe_id = $4
WHERE id = $1
RETURNING id, pos_id, price, recipe_id, created_at
`

type UpdateOrderParams struct {
	ID       int64
	PosID    int32
	Price    int32
	RecipeID int32
}

func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrder,
		arg.ID,
		arg.PosID,
		arg.Price,
		arg.RecipeID,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.PosID,
		&i.Price,
		&i.RecipeID,
		&i.CreatedAt,
	)
	return i, err
}
